# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1db27f99eb723c36942211c9002aafff1bdf2f86cbdf1765d7949c75f9297ea8374921e005c7ee5ba075e8e5c2469bd8027b24c4cc23ed9e832181caf6d32ab

test:
  secret_key_base: 1bf76ba8c38f9dc0743480d15641d961f89169483b1b4fb8f216b3cb555bc38b6aa83a488057809e5a6c21ea81194ad5f2bde79d527be9105371bdcfc2538135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
